In [5]:
# 2nd
import tensorflow as tf

A = tf.constant([[1., 2.],
                 [3., 4.]])
B = tf.constant([[5., 6.],
                 [7., 8.]])

print("Matrix A:\n", A.numpy())
print("Matrix B:\n", B.numpy())

print("\nA + B:\n", tf.add(A, B).numpy())

print("\nA - B:\n", tf.subtract(A, B).numpy())

print("\nA * B:\n", tf.matmul(A, B).numpy())

print("\nTranspose of A:\n", tf.transpose(A).numpy())

print("\nDeterminant of A:", tf.linalg.det(A).numpy())

print("\nInverse of A:\n", tf.linalg.inv(A).numpy())

e_vals, e_vecs = tf.linalg.eig(A)
print("\nEigenvalues of A:", e_vals.numpy())

Matrix A:
 [[1. 2.]
 [3. 4.]]
Matrix B:
 [[5. 6.]
 [7. 8.]]

A + B:
 [[ 6.  8.]
 [10. 12.]]

A - B:
 [[-4. -4.]
 [-4. -4.]]

A * B:
 [[19. 22.]
 [43. 50.]]

Transpose of A:
 [[1. 3.]
 [2. 4.]]

Determinant of A: -2.0

Inverse of A:
 [[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]

Eigenvalues of A: [-0.37228122+0.j  5.372281  +0.j]


In [2]:
# 3rd
import numpy as np

class Perceptron:
    def __init__(self, lr=0.1, epochs=20):
        self.lr = lr
        self.epochs = epochs

    def train(self, X, y):
        self.w = np.zeros(X.shape[1] + 1)

        for _ in range(self.epochs):
            for xi, target in zip(X, y):
                z = np.dot(xi, self.w[1:]) + self.w[0]
                pred = 1 if z >= 0 else 0
                update = self.lr * (target - pred)
                self.w[1:] += update * xi
                self.w[0] += update

    def predict(self, X):
        return [1 if (np.dot(x, self.w[1:]) + self.w[0]) >= 0 else 0 for x in X]


X = np.array([[0,0],[0,1],[1,0],[1,1]])

y_and = np.array([0,0,0,1])
p_and = Perceptron()
p_and.train(X, y_and)
print("AND Gate:", p_and.predict(X))

y_or = np.array([0,1,1,1])
p_or = Perceptron()
p_or.train(X, y_or)
print("OR Gate:", p_or.predict(X))

AND Gate: [0, 0, 0, 1]
OR Gate: [0, 1, 1, 1]


In [3]:
# 4th
import torch
import torch.nn as nn
import torch.optim as optim

X = torch.tensor([[0.,0.],
                  [0.,1.],
                  [1.,0.],
                  [1.,1.]])
y = torch.tensor([[0.],[1.],[1.],[0.]])

class XORNet(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(2, 2)
        self.fc2 = nn.Linear(2, 1)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.sigmoid(self.fc2(x))
        return x

model = XORNet()
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.1)

for epoch in range(2000):
    optimizer.zero_grad()
    out = model(X)
    loss = criterion(out, y)
    loss.backward()
    optimizer.step()

with torch.no_grad():
    preds = model(X)
    print("XOR Output:")
    print(torch.round(preds))

XOR Output:
tensor([[0.],
        [1.],
        [1.],
        [0.]])


In [4]:
# 5th
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


df = pd.read_csv("house_price_full+(2) - house_price_full+(2).csv")

X = df[['bedrooms', 'sqft_living']].values
y = df['price'].values


X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


model = Sequential([
    Dense(2, activation='relu', input_shape=(2,)),
    Dense(1, activation='linear')
])

model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

history = model.fit(
    X_train, y_train,
    epochs=200,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)


loss, mae = model.evaluate(X_test, y_test)
print("Test MAE:", mae)

sample = np.array([[3, 1500]])
sample_scaled = scaler.transform(sample)
prediction = model.predict(sample_scaled)

print("Predicted House Price:", prediction[0][0])

Epoch 1/200


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 416304562176.0000 - mae: 551675.8750 - val_loss: 552508522496.0000 - val_mae: 594698.9375
Epoch 2/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 429996408832.0000 - mae: 565003.1875 - val_loss: 552508522496.0000 - val_mae: 594698.9375
Epoch 3/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 443817492480.0000 - mae: 558466.0625 - val_loss: 552508456960.0000 - val_mae: 594698.8750
Epoch 4/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 443941552128.0000 - mae: 573042.0000 - val_loss: 552508456960.0000 - val_mae: 594698.8750
Epoch 5/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 419767779328.0000 - mae: 553483.2500 - val_loss: 552508456960.0000 - val_mae: 594698.7500
Epoch 6/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 395313774592.0000 - mae: 536702.8750 - val_loss: 552508391424.0000 - val_mae: 594698.7500
Epoch 7/200
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 463691874304.0000 - mae: 584590.5625 - val_loss: 552508325